%% Prettify MATLAB html
% |prettify_MATLAB_html| processes html files generated by MATLAB's |publish| function, adding additional features such as disclosure boxes
% (that can be expanded/collapsed with a mouse-click), and expand-all/collapse-all links that expand/collapse multiple disclosure boxes simultaneously. This
% makes the document more closely resemble "official" MATLAB help files. It also:
%
% * Allows you to easily create internal page links.
% * Provides colour and size formatting options for text.
% * Provides a table style to use when creating tables with html.
% * Automatically enhances the formatting of images and inline code.
% * Allows you to easily create CSS classes and use those classes on elements of the page.
% * Provides the option to apply a "dark" theme to the page.
% 
% please <http://documentation.rf.gd/prettify/prettify_MATLAB_html_helpdoc.html click here> for the full documentation and examples
%