# This file is part of PEET (Particle Estimation for Electron Tomography).
# Copyright 2000-2025 The Regents of the University of Colorado.
# See PEETCopyright.txt for more details.

.PHONY: clean

clean:
	find . -name "*~" -exec rm -rf {} \;

