# This file is part of PEET (Particle Estimation for Electron Tomography).
# Copyright 2000-2012 The Regents of the University of Colorado & BLD3EMC:
#           The Boulder Laboratory For 3D Electron Microscopy of Cells.
# See PEETCopyright.txt for more details.

.PHONY: clean

clean:
	find . -name "*~" -exec rm -rf {} \;

