name: Build macOSX

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-10.15

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Test MATLAB
      run: |
        ls

